name: CI

on:
  push:
    branches:
      - main
      - renovate/*
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      # - name: Run ESLint
      #   run: npx eslint --max-warnings 0 .

      - name: Run Prettier
        run: npx prettier --check .

      - name: Run CSpell
        run: npx cspell "**/*.*"

  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          name: Build
          path: ./configs

  licence:
    name: Check licences

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - uses: fossas/fossa-action@v1.3.1
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
