name: CI

on:
  push:
    branches:
      - main
      - renovate/*
  pull_request:
    branches:
      - main
  workflow_call:

env:
  NODE_VERSION: 20

jobs:
  lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      # - name: Run ESLint
      #   run: npx eslint --max-warnings 0 .

      - name: Run Prettier
        run: npx prettier --check .

      - name: Run CSpell
        run: npx cspell "**/*.*"

  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload configs
        uses: actions/upload-artifact@v3
        with:
          name: Configs
          path: ./configs

  licence:
    name: Check licences

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Check licences
        run: npx license-cop

  codeql:
    name: CodeQL
    uses: ./.github/workflows/codeql.yml
